services:
  hls-streaming-server:
    build: .
  reverse-proxy:
    image: nginx:latest
    ports: 
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on: 
      - hls-streaming-server
