events {}

http {
  proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=hls_cache:10m max_size=1g;
  server {
    listen 80;
    location ~ \.m3u8$ {
      proxy_pass http://hls-streaming-server:8080;
    }
    location ~ \.ts$ {
      proxy_cache hls_cache;
      proxy_cache_valid 200 1y;
      add_header X-Cache-Status $upstream_cache_status;
      proxy_ignore_headers Cache-Control;
      proxy_pass http://hls-streaming-server:8080;
    }
    add_header X-Cache-Status $upstream_cache_status;
  }
}
